# Generated by Django 2.2 on 2019-04-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boxes',
            new_name='Box',
        ),
    ]
