# Generated by Django 2.2 on 2019-04-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20190424_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='color',
            new_name='name',
        ),
    ]
